### ISSUE TITLE
Isolate Script into /Script

### ISSUE THREAD

**Issue by vermorel** [Lokad/BitcoinNet#12]
Bitcoin includes a DSL named ‘Script’. The logic associated to this DSL is somewhat complex, and involves many classes, all bundled in Script.cs and maybe a few other files. Those files should be isolated into a proper /Script folder and namespace.

**Comment by osman-turan** [comment]
If I move into `/Script` folder, it makes sense to set namespace as `BitcoinNet.Script`. But, this conflicts with `Script` class. So, in order to use `Script` class, we need to use `Script.Script` in order to resolve conflict for the compiler. Do you have any idea to solve this naming dilemma? 🙂

**Comment by vermorel** [comment]
I suggest to rename the namespace `Script` as `BitcoinNet.Scripting`.

**Comment by osman-turan** [comment]
For the sake of consistency with namespace naming convention, I had to rename the folder as `Scripting`. I also refactored `ScriptEvaluationContext.cs` and `ScriptReader.cs` besides `Script.cs`. Because, they are all related to script evaluation. But, I excluded script templates (`StandardScripts.cs` and `StandardScriptTemplate.cs`).
